
DROP TABLE IF EXISTS `characters_fake`;

CREATE TABLE `characters_fake` (
  `name` VARCHAR(36) NOT NULL,
  `race` MEDIUMINT(3) NOT NULL DEFAULT '0',
  `class` MEDIUMINT(3) NOT NULL DEFAULT '0',
  `level` MEDIUMINT(3) NOT NULL DEFAULT '0',
  `zone` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `gender` MEDIUMINT(3) NOT NULL DEFAULT '0'
) ENGINE=MYISAM DEFAULT CHARSET=latin1;
